server:
  port: ${SERVER_PORT_DEV:8081}

spring:
  application:
    name: ${APP_NAME_DEV:api-kt-dev}
  data:
    mongodb:
      uri: ${MONGODB_URI_DEV:mongodb://localhost:27017/apiKtDev}
      database: ${MONGODB_DATABASE_DEV:apiKtDev}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: ${MONGO_LOG_LEVEL_DEV:DEBUG}
    com.onyell: ${LOG_LEVEL_DEV:DEBUG} 