server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: ${APP_NAME:api-kt}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/apiKt}
      database: ${MONGODB_DATABASE:apiKt}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: ${MONGO_LOG_LEVEL:DEBUG}
    com.onyell: ${LOG_LEVEL:INFO}
